playerInventory:
  preventItemPickup: false
  preventItemDrop: false
  preventMoveInOwnInventory: false
  clearOnJoin: false

preventFallingIntoVoid: false

jumpPads:
  main1:
    padLocation: world 5 64 5
    height: 0.2
    distance: 3
