playerInventory:
  preventItemPickup: false
  preventItemDrop: false
  preventMoveInOwnInventory: false
  clearOnJoin: false

preventFallingIntoVoid: false
preventPlayerDamage: false
preventPlayerHunger: false

forceTime:
  enabled: false
  timeToForce: 6000

forceWeather:
  enabled: false
  weatherToForce: SUN

jumpPads:
  main1:
    padLocation: world 5 64 5
    height: 0.2
    distance: 3

portals:
  main:
    worldName: world
    pos1: 10 64 10
    pos2: 15 69 10
    teleportToOnEnter: world 0 64 0
    menuToOpenOnEnter: main
    spawnOnMenuClose: false
    teleportToOnMenuClose: world 5 64 5
    hidePlayerWhileInMenu: false
